export const data = [
  {
    id: 1,
    nombre: "lorem ipsum",
    edad: "30",
    especialidad: "Front-End",
    framework: "Next js",
    años_experiencia: "3 años",
    pais: "Argentina",
    ciudad: "Buenos Aires",
  },
  {
    id: 2,
    nombre: "lorem ipsum",
    edad: "30",
    especialidad: "Back-End",
    framework: "Node/Express js",
    años_experiencia: "3 años",
    pais: "Argentina",
    ciudad: "Buenos Aires",
  },
  {
    id: 3,
    nombre: "lorem ipsum",
    edad: "30",
    especialidad: "Front-End",
    framework: "React js",
    años_experiencia: "3 años",
    pais: "Argentina",
    ciudad: "Buenos Aires",
  },
  {
    id: 4,
    nombre: "lorem ipsum",
    edad: "30",
    especialidad: "Front-End",
    framework: "Angular js",
    años_experiencia: "3 años",
    pais: "Argentina",
    ciudad: "Buenos Aires",
  },
  {
    id: 5,
    nombre: "lorem ipsum",
    edad: "30",
    especialidad: "Back-End",
    framework: "Nest js",
    años_experiencia: "3 años",
    pais: "Argentina",
    ciudad: "Buenos Aires",
  },
  {
    id: 6,
    nombre: "lorem ipsum",
    edad: "30",
    especialidad: "Front-End",
    framework: "Vue js",
    años_experiencia: "3 años",
    pais: "Argentina",
    ciudad: "Buenos Aires",
  },
];
